# Generated by Django 4.2.7 on 2023-11-11 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fastcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='not indicated', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/users_photo'),
        ),
        migrations.AddField(
            model_name='page',
            name='salary',
            field=models.CharField(default='not indicated', max_length=20),
        ),
        migrations.AddField(
            model_name='page',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
