# Generated by Django 4.2.7 on 2023-11-11 23:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fastcase', '0003_page_description_alter_page_name_alter_page_salary_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Info',
        ),
    ]
